version: '3.4'

services:
  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile

  #library.api:
  #  image: ${DOCKER_REGISTRY-}libraryapi
  #  build:
  #    context: .
  #    dockerfile: Services/Library/Library.API/Dockerfile

