version: '3.4'

services:
  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile
    networks:
      - frontend
      - backend

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile
    networks:
      - backend
    depends_on:
      - database
      - messagebus

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    networks:
      - backend
    depends_on:
      - database
      - messagebus

  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Services/Library/Library.API/Dockerfile
    networks:
      - backend
    depends_on:
      - database
      - messagebus

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    networks:
      - backend
    depends_on:
      - messagebus

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    networks:
      - backend

  messagebus:
    image: masstransit/rabbitmq
    networks:
      - backend

  userdata.api:
    image: ${DOCKER_REGISTRY-}userdataapi
    build:
      context: .
      dockerfile: Services/UserData/UserData.API/Dockerfile
    networks:
      - backend
    depends_on:
      - database
      - messagebus

networks:
  frontend:
  backend:
