version: '3.4'
name: Coursenest-Dev

services:
  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "21000:80"

  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=AuthenticationDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
      - Jwt__AccessTokenLifetime=60
      - Jwt__RefreshTokenLifetime=180
    #ports:
    #  - "21001:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=IdentityDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
    #ports:
    #  - "21002:80"

  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=LibraryDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
    #ports:
    #  - "21003:80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
    #ports:
    #  - "21004:80"

  userdata.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=UserDataDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
    #ports:
    #  - "21005:80"

  database:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
    volumes:
      - coursenest-dev-db:/var/opt/mssql
    ports:
      - "1433:1433"

  messagebus:
    volumes:
      - coursenest-dev-mb:/var/lib/rabbitmq
    ports:
    #  - "5672:5672"
      - "15672:15672"

volumes:
  coursenest-dev-db:
    external: true
  coursenest-dev-mb:
    external: true