version: '3.4'

services:
  #gatewayapi:
  #  environment:
  #    - Jwt__Key=Yh2k7QSu4l8CZg5p
  #  ports:
  #    - "21000:80"

  authentication.api:
    environment:
      - Database__ConnectionString=Server=database;Database=AuthenticationDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
      - Jwt__SecretKey=1234567890123456
      - Jwt__AccessTokenLifetime=10
      - Jwt__RefreshTokenLifetime=60
    ports:
      - "21001:80"

  identity.api:
    environment:
      - Database__ConnectionString=Server=database;Database=IdentityDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
    ports:
      - "21002:80"

  library.api:
    environment:
      - Database__ConnectionString=Server=database;Database=LibraryDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
    ports:
      - "21003:80"

  payment.api:
    environment:
      - MassTransit__Host=messagebus
    ports:
      - "21004:80"

  userdata.api:
    environment:

    ports:
      - "80"

  database:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
    volumes:
      - coursenest-dev:/var/opt/mssql
    ports:
      - "1433:1433"

  messagebus:
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  coursenest-dev:
    external: true
