version: "3.4"
name: coursenest

services:
  web.user:
    ports:
      - "21001:5000"

  web.admin:
    ports:
      - "21002:5000"

  gatewayapi:
    ports:
      - "21000:80"

  authentication.api:
    environment:
      - Database__ConnectionString=Server=database;Database=AuthenticationDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api
      - Jwt__AccessTokenLifetime=60
      - Jwt__RefreshTokenLifetime=180

  identity.api:
    environment:
      - Database__ConnectionString=Server=database;Database=IdentityDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api

  library.api:
    environment:
      - Database__ConnectionString=Server=database;Database=LibraryDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api

  payment.api:
    environment:
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api

  userdata.api:
    environment:
      - Database__ConnectionString=Server=database;Database=UserDataDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - MassTransit__Host=messagebus
      - Jwt__SigningKey=1234567890123456
      - Jwt__Issuer=http://authentication.api

  database:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
    volumes:
      - coursenest-prod-db:/var/opt/mssql

  messagebus:
    volumes:
      - coursenest-prod-mb:/var/lib/rabbitmq

  reverseproxy:
    volumes:
      - ./ReverseProxy/Caddyfile-Prod:/etc/caddy/Caddyfile
    ports:
      - "20000:20000"
      - "20001:20001"

volumes:
  coursenest-prod-db:
    external: true
  coursenest-prod-mb:
    external: true
