version: '3.4'

services:
  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=Yh2k7QSu4l8CZg5p
    ports:
      - "21000:80"

  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=AuthenticationDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureDeleted=true
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
      - Jwt__SecretKey=1234567890123456
      - Jwt__AccessTokenLifetime=10
      - Jwt__RefreshTokenLifetime=60
    ports:
      - "21001:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=IdentityDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureDeleted=true
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
    ports:
      - "21002:80"

  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Server=database;Database=LibraryDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
      - Database__EnsureDeleted=true
      - Database__EnsureCreated=true
      - MassTransit__Host=messagebus
    ports:
      - "21003:80"

  database:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"

  messagebus:
    ports:
      - "5672:5672"
      - "15672:15672"
